### ISSUE TITLE
No builds runnings seeing plugin errors

### ISSUE THREAD

**Issue by omkarghalsasi** [jonnyzzz/TeamCity.Node#147]
We recently encountered an issue with our Teamcity enterprise server when, the builds suddenly stopped running eventhough the agents were idle. The build queue was growing continuously but no builds actually executed. The logs are filled with following error:
[2017-12-19 05:51:35,343] WARN - verSide.impl.BuildServerRunner - Unexpected exception occurred in Flush Queue 1, operation will be repeated 
java.lang.RuntimeException: java.lang.NoClassDefFoundError: com/jonnyzzz/teamcity/plugins/node/server/NVMRunType$getRunnerPropertiesProcessor$1
at jetbrains.buildServer.util.ExceptionUtil.rethrowAsRuntimeException(ExceptionUtil.java:72)
at jetbrains.buildServer.serverSide.RawCompatibilityCalculator.calculateCompatibility(RawCompatibilityCalculator.java:12)
at jetbrains.buildServer.serverSide.impl.BuildPromotionImpl$CandidatesCache.getCompatibilityMap(BuildPromotionImpl.java:6)
at jetbrains.buildServer.serverSide.impl.BuildPromotionImpl.getCompatibleAgents(BuildPromotionImpl.java:1378)
at jetbrains.buildServer.serverSide.impl.buildDistribution.BuildAgentDistributor.getPromotionCompatibleAgents(BuildAgentDistributor.java:15)
at jetbrains.buildServer.serverSide.impl.buildDistribution.BuildAgentDistributor.access$200(BuildAgentDistributor.java:12)
at jetbrains.buildServer.serverSide.impl.buildDistribution.BuildAgentDistributor$CompatibleAgentsCalculatorWithoutReasons.getCompatibleAgents(BuildAgentDistributor.java:6)
at jetbrains.buildServer.serverSide.impl.buildDistribution.BuildAgentDistributor.getCompatibleCandidates(BuildAgentDistributor.java:13)
at jetbrains.buildServer.serverSide.impl.buildDistribution.AbstractDistributor.doDistribute(AbstractDistributor.java:12)
at jetbrains.buildServer.serverSide.impl.buildDistribution.DefaultBuildDistributor.assignBuildsToAgents(DefaultBuildDistributor.java:9)
at jetbrains.buildServer.serverSide.impl.buildDistribution.BuildDistributorProxy.assignBuildsToAgents(BuildDistributorProxy.java:6)
at jetbrains.buildServer.serverSide.impl.FlushQueueForConnectedAgents.distribute(FlushQueueForConnectedAgents.java:15)
at jetbrains.buildServer.serverSide.impl.FlushQueueAction$2.distribute(FlushQueueAction.java:2)
at jetbrains.buildServer.serverSide.impl.FlushQueueTemplate.flushRealAgents(FlushQueueTemplate.java:8)
at jetbrains.buildServer.serverSide.impl.FlushQueueTemplate.access$100(FlushQueueTemplate.java:53)
at jetbrains.buildServer.serverSide.impl.FlushQueueTemplate$2.run(FlushQueueTemplate.java:1)
at jetbrains.buildServer.serverSide.impl.FlushQueueAction$QueueAction.run(FlushQueueAction.java:1)
at jetbrains.buildServer.serverSide.impl.cleanup.ServerCleanupState.runUnderLock(ServerCleanupState.java:5)
at jetbrains.buildServer.serverSide.impl.cleanup.ServerCleanupState.runReadAction(ServerCleanupState.java:37)
at jetbrains.buildServer.serverSide.impl.cleanup.ServerCleanupManagerImpl.executeWithInactiveCleanup(ServerCleanupManagerImpl.java:173)
at jetbrains.buildServer.serverSide.impl.cleanup.ServerCleanupManagerImpl$$FastClassBySpringCGLIB$$ba2c8525.invoke(<generated>)
at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:720)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
at jetbrains.buildServer.serverSide.impl.auth.TeamCityMethodSecurityInterceptor.invoke(TeamCityMethodSecurityInterceptor.java:10)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
at org.springframework.aop.framework.CglibAopProxy$FixedChainStaticTargetInterceptor.intercept(CglibAopProxy.java:604)
at jetbrains.buildServer.serverSide.impl.cleanup.ServerCleanupManagerImpl$$EnhancerBySpringCGLIB$$b9a5d23b.executeWithInactiveCleanup(<generated>)
at jetbrains.buildServer.serverSide.impl.FlushQueueAction.flushQueue(FlushQueueAction.java:3)
at jetbrains.buildServer.serverSide.impl.BuildServerImpl.flushQueue(BuildServerImpl.java:82)
at jetbrains.buildServer.serverSide.impl.BuildServerRunner$2.doSomething(BuildServerRunner.java:2)
at jetbrains.buildServer.serverSide.impl.BuildServerRunner$BuildServerWorker.runAction(BuildServerRunner.java:43)
at jetbrains.buildServer.serverSide.impl.BuildServerRunner$BuildServerWorker.run(BuildServerRunner.java:52)
at java.lang.Thread.run(Unknown Source)
We had to restart our teamcity server for builds to resume running. Can you please advise how do we go about understanding the root cause of the issue? 

We are currently using Teamcity.Node 1.0.90 and our TC version is 10.0.4 at the moment.

Regards,
Omkar Ghalsasi

**Comment by omkarghalsasi** [comment]
@jonnyzzz can you please help us out here?

**Comment by jonnyzzz** [comment]
I see nothing suspicious in the code. Please make sure you have not changed TeamCity server files on the disk. Was restart helpful?

**Comment by omkarghalsasi** [comment]
Hey Eugene,

Thanks for getting back. Yes the restart definitely helped. Files were not changed from our end. Few weeks before the issue we did have a change that moved teamcity data directory to network drive. But after that change everything was fine for 2 weeks until this issue. Do you think moving data to network drive could cause an issue of this magnitude? Also from your understanding what do you think the error means exactly?

Regards,
Omkar

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by jonnyzzz** [comment]
My guess was that the network share get unavailable for a short time.
Plugin classes are in the directory too. Thus At the moment JVM failed to
find the file and load the class. It might be the reason of the error you
saw.

**Comment by jonnyzzz** [comment]
Fixed in #150
