### ISSUE TITLE
Need Help. i have this error Failed to start build runner 'jonnyzzz.grunt' . Help me with it pls 

### ISSUE THREAD

**Issue by sergeyRaskinIqp** [jonnyzzz/TeamCity.Node#150]
tep 1/3: nodeInstall (Node.js NVM Installer) (17s)
[12:19:22]Step 2/3: npm i (Node.js NPM) (47s)
[12:20:09]Step 3/3: grunt build (Grunt)
[12:20:09][Step 3/3] Failed to start build runner 'jonnyzzz.grunt'
[12:20:09]
[Step 3/3] java.lang.NoClassDefFoundError: com/google/gson/Gson
	at com.jonnyzzz.teamcity.plugins.node.agent.BaseService.generateAllParametersJSON(JsService.kt:205)
	at com.jonnyzzz.teamcity.plugins.node.agent.BaseService.generateDefaultTeamCityParametersJSON(JsService.kt:83)
	at com.jonnyzzz.teamcity.plugins.node.agent.grunt.GruntSession.makeProgramCommandLine(GruntServiceFactory.kt:99)
	at jetbrains.buildServer.agent.runner2.SingleCommandLineBuildSessionAdapter.makeProgramCommandLine(SingleCommandLineBuildSessionAdapter.java:53)
	at jetbrains.buildServer.agent.runner2.GenericCommandLineBuildProcess.executeProcess(GenericCommandLineBuildProcess.java:71)
	at jetbrains.buildServer.agent.runner2.GenericCommandLineBuildProcess.waitFor(GenericCommandLineBuildProcess.java:257)
	at jetbrains.buildServer.agent.impl.buildStages.runnerStages.start.CallRunnerStage.doBuildStage(CallRunnerStage.java:59)
	at jetbrains.buildServer.agent.impl.buildStages.RunnerStagesExecutor$1.callStage(RunnerStagesExecutor.java:25)
	at jetbrains.buildServer.agent.impl.buildStages.RunnerStagesExecutor$1.callStage(RunnerStagesExecutor.java:18)
	at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.callRunStage(StagesExecutor.java:78)
	at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.doStages(StagesExecutor.java:37)
	at jetbrains.buildServer.agent.impl.buildStages.RunnerStagesExecutor.doStages(RunnerStagesExecutor.java:18)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.RunnerContextExecutor.callRunnerStages(RunnerContextExecutor.java:43)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.StepExecutor.processNextStep(StepExecutor.java:25)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.executeRunnerStep(ForEachBuildRunnerStage.java:138)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.runStep(ForEachBuildRunnerStage.java:123)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.executeBuildRunners(ForEachBuildRunnerStage.java:83)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.doBuildStage(ForEachBuildRunnerStage.java:44)
	at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor$1.callStage(BuildStagesExecutor.java:31)
	at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor$1.callStage(BuildStagesExecutor.java:24)
	at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.callRunStage(StagesExecutor.java:78)
	at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.doStages(StagesExecutor.java:37)
	at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor.doStages(BuildStagesExecutor.java:24)
	at jetbrains.buildServer.agent.impl.BuildRunActionImpl.doStages(BuildRunActionImpl.java:70)
	at jetbrains.buildServer.agent.impl.BuildRunActionImpl.runBuild(BuildRunActionImpl.java:50)
	at jetbrains.buildServer.agent.impl.BuildAgentImpl.doActualBuild(BuildAgentImpl.java:288)
	at jetbrains.buildServer.agent.impl.BuildAgentImpl.access$100(BuildAgentImpl.java:53)
	at jetbrains.buildServer.agent.impl.BuildAgentImpl$1.run(BuildAgentImpl.java:252)
	at java.lang.Thread.run(Thread.java:745)
[12:20:09][Step 3/3] Step grunt build (Grunt) failed with unexpected error

**Comment by jonnyzzz** [comment]
Please make sure you are using the latest build. gson library is bundled, so it is supposed to work

**Comment by satyaprakashv** [comment]
Hi jonnyzzz, 
I am facing the similar issue for 'jonnyzzz.gulp'
Please suggest - 
Step 3/6: Generate Build Transformation for Nuget Package (Gulp)
[10:07:15][Step 3/6] Failed to start build runner 'jonnyzzz.gulp'
[10:07:15]
[Step 3/6] java.lang.NoClassDefFoundError: com/google/gson/Gson
	at com.jonnyzzz.teamcity.plugins.node.agent.BaseService.generateAllParametersJSON(JsService.kt:205)
	at com.jonnyzzz.teamcity.plugins.node.agent.BaseService.generateDefaultTeamCityParametersJSON(JsService.kt:83)
	at com.jonnyzzz.teamcity.plugins.node.agent.gulp.GulpSession.makeProgramCommandLine(GulpServiceFactory.kt:99)

**Comment by jonnyzzz** [comment]
Please update the plugin to the most recent version. I've included the gson
library explicitly there.

Best regards,
Eugene Petrenko

**Comment by satyaprakashv** [comment]
Hey Jonnyzzz,
I found the older version of node plugin and installed the older version (jonnyzzz.node.zip) plugin and it worked for me, but i was expecting to work the same gulp runner with newer version as well.
I had issue while i had installed the latest  - teamcity-node-2.0.7.zip.

Is there any fix needed. Or do i need to change anything in my Team City build steps configuration.

**Comment by jonnyzzz** [comment]
Nope, the error - NoClassDefFound means the plugin is not able to work on
the TeamCity.
It does not depend on any settings from your side.
I checked once moreto make sure `gson` library is indeed bundled with the
plugin - it did not.
I'll patch the way the plugin is being compiled and packed to make sure
libraries are not missing in there

Best regards,
Eugene Petrenko

**Comment by satyaprakashv** [comment]
Awesome, So please let me know when can i take the latest build and then can install the latest plugin and test,

Regards
Satya

**Comment by jonnyzzz** [comment]
Please check if the fresh build works for you
