### ISSUE TITLE
"Incompatible runner" after upgrading to 2.0.10

### ISSUE THREAD

**Issue by htonheim** [jonnyzzz/TeamCity.Node#152]
After upgrading the plugin from 1.0.124 to 2.0.10, none of the builds using the plugin will start because of "no compatible agents". The reason given is "Incompatible runner: Grunt" or "Incompatible runner: NPM". This is consistent across all our builds using the plugin. Downgrading to 1.0.124 fixes the issues.

Our build agents are running on Windows Server 2008 R2 SP1.

**Comment by DanHarman** [comment]
I have the same problem running agents on windows server 2012.

**Comment by hgontijo** [comment]
Facing the same issue on version 2.0.10. Running:
- Linux, version 3.10.0-514.16.1.el7.x86_64
- TeamCity Enterprise 2017.2.3 (build 51047)

Agent parameters:
```
node.js     | Use_NodeJS_Install_Runner
node.js.npm | Use_NodeJS_Install_Runner
node.js.nvm | yes
```

**Comment by Carevich** [comment]
Same issue "Incompatible runner: Node.js NPM".
- Windows server 2016
- TeamCity Professional 2017.2.3 (build 51047)

**Comment by pnm-i** [comment]
Sure, here is error logs after restart teamcity server.

```
[2018-05-16 08:54:37,686]  ERROR - gins.spring.SpringPluginLoader - Error loading plugin 'teamcity-node-agent-2.0.10': Failed to initialize spring context: Error creating bean with name 'com.jonnyzzz.teamcity.plugins.node.agent.nvm.NVMDownloader#0' defined in Byte array resource [plugin: teamcity-node-agent-2.0.10#teamcity-node-agent-2.0.10.jar!/META-INF/build-agent-plugin-node.xml]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.jonnyzzz.teamcity.plugins.node.agent.nvm.HttpClientWrapperImpl#0': Failed to introspect bean class [com.jonnyzzz.teamcity.plugins.node.agent.nvm.HttpClientWrapperImpl] for lookup method metadata: could not find class that it depends on; nested exception is java.lang.NoClassDefFoundError: org/apache/http/HttpRequest 
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'com.jonnyzzz.teamcity.plugins.node.agent.nvm.NVMDownloader#0' defined in Byte array resource [plugin: teamcity-node-agent-2.0.10#teamcity-node-agent-2.0.10.jar!/META-INF/build-agent-plugin-node.xml]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.jonnyzzz.teamcity.plugins.node.agent.nvm.HttpClientWrapperImpl#0': Failed to introspect bean class [com.jonnyzzz.teamcity.plugins.node.agent.nvm.HttpClientWrapperImpl] for lookup method metadata: could not find class that it depends on; nested exception is java.lang.NoClassDefFoundError: org/apache/http/HttpRequest
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:749)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:189)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1193)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1095)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:513)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543)
	at jetbrains.buildServer.plugins.spring.SpringPluginLoader.pluginClassesLoaded(SpringPluginLoader.java:102)
	at sun.reflect.GeneratedMethodAccessor16.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at jetbrains.buildServer.util.EventDispatcher$3.run(EventDispatcher.java:126)
	at jetbrains.buildServer.util.NamedThreadFactory.executeWithNewThreadName(NamedThreadFactory.java:71)
	at jetbrains.buildServer.util.EventDispatcher.dispatch(EventDispatcher.java:120)
	at jetbrains.buildServer.util.EventDispatcher$2.invoke(EventDispatcher.java:70)
	at com.sun.proxy.$Proxy14.pluginClassesLoaded(Unknown Source)
	at jetbrains.buildServer.plugins.PluginManagerImpl$2.visitPlugin(PluginManagerImpl.java:140)
	at jetbrains.buildServer.plugins.PluginsCollection$6.run(PluginsCollection.java:261)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.jonnyzzz.teamcity.plugins.node.agent.nvm.HttpClientWrapperImpl#0': Failed to introspect bean class [com.jonnyzzz.teamcity.plugins.node.agent.nvm.HttpClientWrapperImpl] for lookup method metadata: could not find class that it depends on; nested exception is java.lang.NoClassDefFoundError: org/apache/http/HttpRequest
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.determineCandidateConstructors(AutowiredAnnotationBeanPostProcessor.java:269)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.determineConstructorsFromBeanPostProcessors(AbstractAutowireCapableBeanFactory.java:1118)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1091)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:513)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1138)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1066)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:835)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:741)
	... 28 more
Caused by: java.lang.NoClassDefFoundError: org/apache/http/HttpRequest
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at jetbrains.buildServer.plugins.classLoaders.TeamCityClassLoader.doLoadClass(TeamCityClassLoader.java:73)
	at jetbrains.buildServer.plugins.classLoaders.TeamCityClassLoader.loadClass(TeamCityClassLoader.java:40)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethods(Class.java:1975)
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:613)
	at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:524)
	at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:510)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.determineCandidateConstructors(AutowiredAnnotationBeanPostProcessor.java:247)
	... 41 more
Caused by: java.lang.ClassNotFoundException: Class 'org.apache.http.HttpRequest' was not found
	at jetbrains.buildServer.plugins.classLoaders.TeamCityClassLoader.doLoadClass(TeamCityClassLoader.java:85)
	at jetbrains.buildServer.plugins.classLoaders.TeamCityClassLoader.loadClass(TeamCityClassLoader.java:40)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 60 more
```

**Comment by rojobull** [comment]
Hi. I too had the same issue with version 2.0.10. Reverting to version 1.0.124 resolved the issue for now.

**Comment by jakehockey10** [comment]
Any update on this?

**Comment by andy-culshaw** [comment]
This looks like a missing httpcore dependency. You can get round it by downloading http://repo1.maven.org/maven2/org/apache/httpcomponents/httpcore/4.2.5/httpcore-4.2.5.jar and adding it to .../plugins/teamcity-node-agent-2.0.10/lib

**Comment by jakehockey10** [comment]
I don't have this error in my TeamCity Build agent logs.

**Comment by jakehockey10** [comment]
I stepped back for a bit and realized that Notepad++ makes this easy.  Found that what I was looking for was in `wrapper.log`.  Here is the important piece:

``` log
INFO   | jvm 1    | 2018/06/07 01:28:13 | [2018-06-07 01:28:13,891]   WARN - ig.BuildAgentConfigurablePaths - Failed to set workDir from 'W:\BuildAgent\work'. Cannot create directory: W:\BuildAgent\work. Default value '../work' will be used.  
INFO   | jvm 1    | 2018/06/07 01:28:17 | [2018-06-07 01:28:17,487]   WARN - inLoader$TeamCityPluginContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'com.jonnyzzz.teamcity.plugins.node.agent.nvm.NVMDownloader#0' defined in Byte array resource [plugin: teamcity-node-agent-2.0.10#teamcity-node-agent-2.0.10.jar!/META-INF/build-agent-plugin-node.xml]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.jonnyzzz.teamcity.plugins.node.agent.nvm.HttpClientWrapperImpl#0': Failed to introspect bean class [com.jonnyzzz.teamcity.plugins.node.agent.nvm.HttpClientWrapperImpl] for lookup method metadata: could not find class that it depends on; nested exception is java.lang.NoClassDefFoundError: org/apache/http/HttpRequest  
INFO   | jvm 1    | 2018/06/07 01:28:17 | [2018-06-07 01:28:17,487]  ERROR - gins.spring.SpringPluginLoader - Error loading plugin 'teamcity-node-agent-2.0.10': Failed to initialize spring context: Error creating bean with name 'com.jonnyzzz.teamcity.plugins.node.agent.nvm.NVMDownloader#0' defined in Byte array resource [plugin: teamcity-node-agent-2.0.10#teamcity-node-agent-2.0.10.jar!/META-INF/build-agent-plugin-node.xml]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.jonnyzzz.teamcity.plugins.node.agent.nvm.HttpClientWrapperImpl#0': Failed to introspect bean class [com.jonnyzzz.teamcity.plugins.node.agent.nvm.HttpClientWrapperImpl] for lookup method metadata: could not find class that it depends on; nested exception is java.lang.NoClassDefFoundError: org/apache/http/HttpRequest  
INFO   | jvm 1    | 2018/06/07 01:28:17 | org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'com.jonnyzzz.teamcity.plugins.node.agent.nvm.NVMDownloader#0' defined in Byte array resource [plugin: teamcity-node-agent-2.0.10#teamcity-node-agent-2.0.10.jar!/META-INF/build-agent-plugin-node.xml]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.jonnyzzz.teamcity.plugins.node.agent.nvm.HttpClientWrapperImpl#0': Failed to introspect bean class [com.jonnyzzz.teamcity.plugins.node.agent.nvm.HttpClientWrapperImpl] for lookup method metadata: could not find class that it depends on; nested exception is java.lang.NoClassDefFoundError: org/apache/http/HttpRequest 
INFO   | jvm 1    | 2018/06/07 01:28:17 | 	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:749) 
INFO   | jvm 1    | 2018/06/07 01:28:17 | 	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:189) 
INFO   | jvm 1    | 2018/06/07 01:28:17 | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1193) 
INFO   | jvm 1    | 2018/06/07 01:28:17 | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1095) 
INFO   | jvm 1    | 2018/06/07 01:28:17 | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:513) 
INFO   | jvm 1    | 2018/06/07 01:28:17 | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483) 
INFO   | jvm 1    | 2018/06/07 01:28:17 | 	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) 
INFO   | jvm 1    | 2018/06/07 01:28:17 | 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) 
INFO   | jvm 1    | 2018/06/07 01:28:17 | 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) 
INFO   | jvm 1    | 2018/06/07 01:28:17 | 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) 
INFO   | jvm 1    | 2018/06/07 01:28:17 | 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761) 
INFO   | jvm 1    | 2018/06/07 01:28:17 | 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867) 
INFO   | jvm 1    | 2018/06/07 01:28:17 | 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543) 
INFO   | jvm 1    | 2018/06/07 01:28:17 | 	at jetbrains.buildServer.plugins.spring.SpringPluginLoader.pluginClassesLoaded(SpringPluginLoader.java:102) 
INFO   | jvm 1    | 2018/06/07 01:28:17 | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
INFO   | jvm 1    | 2018/06/07 01:28:17 | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 
INFO   | jvm 1    | 2018/06/07 01:28:17 | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
INFO   | jvm 1    | 2018/06/07 01:28:17 | 	at java.lang.reflect.Method.invoke(Method.java:498) 
INFO   | jvm 1    | 2018/06/07 01:28:17 | 	at jetbrains.buildServer.util.EventDispatcher$3.run(EventDispatcher.java:126) 
INFO   | jvm 1    | 2018/06/07 01:28:17 | 	at jetbrains.buildServer.util.NamedThreadFactory.executeWithNewThreadName(NamedThreadFactory.java:71) 
INFO   | jvm 1    | 2018/06/07 01:28:17 | 	at jetbrains.buildServer.util.EventDispatcher.dispatch(EventDispatcher.java:120) 
INFO   | jvm 1    | 2018/06/07 01:28:17 | 	at jetbrains.buildServer.util.EventDispatcher$2.invoke(EventDispatcher.java:70) 
INFO   | jvm 1    | 2018/06/07 01:28:17 | 	at com.sun.proxy.$Proxy14.pluginClassesLoaded(Unknown Source) 
INFO   | jvm 1    | 2018/06/07 01:28:17 | 	at jetbrains.buildServer.plugins.PluginManagerImpl$2.visitPlugin(PluginManagerImpl.java:140) 
INFO   | jvm 1    | 2018/06/07 01:28:17 | 	at jetbrains.buildServer.plugins.PluginsCollection$6.run(PluginsCollection.java:261) 
INFO   | jvm 1    | 2018/06/07 01:28:17 | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) 
INFO   | jvm 1    | 2018/06/07 01:28:17 | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
INFO   | jvm 1    | 2018/06/07 01:28:17 | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) 
INFO   | jvm 1    | 2018/06/07 01:28:17 | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) 
INFO   | jvm 1    | 2018/06/07 01:28:17 | 	at java.lang.Thread.run(Thread.java:745) 
INFO   | jvm 1    | 2018/06/07 01:28:17 | Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.jonnyzzz.teamcity.plugins.node.agent.nvm.HttpClientWrapperImpl#0': Failed to introspect bean class [com.jonnyzzz.teamcity.plugins.node.agent.nvm.HttpClientWrapperImpl] for lookup method metadata: could not find class that it depends on; nested exception is java.lang.NoClassDefFoundError: org/apache/http/HttpRequest 
INFO   | jvm 1    | 2018/06/07 01:28:17 | 	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.determineCandidateConstructors(AutowiredAnnotationBeanPostProcessor.java:269) 
INFO   | jvm 1    | 2018/06/07 01:28:17 | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.determineConstructorsFromBeanPostProcessors(AbstractAutowireCapableBeanFactory.java:1118) 
INFO   | jvm 1    | 2018/06/07 01:28:17 | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1091) 
INFO   | jvm 1    | 2018/06/07 01:28:17 | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:513) 
INFO   | jvm 1    | 2018/06/07 01:28:17 | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483) 
INFO   | jvm 1    | 2018/06/07 01:28:17 | 	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) 
INFO   | jvm 1    | 2018/06/07 01:28:17 | 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) 
INFO   | jvm 1    | 2018/06/07 01:28:17 | 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) 
INFO   | jvm 1    | 2018/06/07 01:28:17 | 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) 
INFO   | jvm 1    | 2018/06/07 01:28:17 | 	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:208) 
INFO   | jvm 1    | 2018/06/07 01:28:17 | 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1138) 
INFO   | jvm 1    | 2018/06/07 01:28:17 | 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1066) 
INFO   | jvm 1    | 2018/06/07 01:28:17 | 	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:835) 
INFO   | jvm 1    | 2018/06/07 01:28:17 | 	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:741) 
INFO   | jvm 1    | 2018/06/07 01:28:17 | 	... 29 more 
INFO   | jvm 1    | 2018/06/07 01:28:17 | Caused by: java.lang.NoClassDefFoundError: org/apache/http/HttpRequest 
INFO   | jvm 1    | 2018/06/07 01:28:17 | 	at java.lang.ClassLoader.defineClass1(Native Method) 
INFO   | jvm 1    | 2018/06/07 01:28:17 | 	at java.lang.ClassLoader.defineClass(ClassLoader.java:763) 
INFO   | jvm 1    | 2018/06/07 01:28:17 | 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) 
INFO   | jvm 1    | 2018/06/07 01:28:17 | 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467) 
INFO   | jvm 1    | 2018/06/07 01:28:17 | 	at java.net.URLClassLoader.access$100(URLClassLoader.java:73) 
INFO   | jvm 1    | 2018/06/07 01:28:17 | 	at java.net.URLClassLoader$1.run(URLClassLoader.java:368) 
INFO   | jvm 1    | 2018/06/07 01:28:17 | 	at java.net.URLClassLoader$1.run(URLClassLoader.java:362) 
INFO   | jvm 1    | 2018/06/07 01:28:17 | 	at java.security.AccessController.doPrivileged(Native Method) 
INFO   | jvm 1    | 2018/06/07 01:28:17 | 	at java.net.URLClassLoader.findClass(URLClassLoader.java:361) 
INFO   | jvm 1    | 2018/06/07 01:28:17 | 	at jetbrains.buildServer.plugins.classLoaders.TeamCityClassLoader.doLoadClass(TeamCityClassLoader.java:73) 
INFO   | jvm 1    | 2018/06/07 01:28:17 | 	at jetbrains.buildServer.plugins.classLoaders.TeamCityClassLoader.loadClass(TeamCityClassLoader.java:40) 
INFO   | jvm 1    | 2018/06/07 01:28:17 | 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) 
INFO   | jvm 1    | 2018/06/07 01:28:17 | 	at java.lang.Class.getDeclaredMethods0(Native Method) 
INFO   | jvm 1    | 2018/06/07 01:28:17 | 	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) 
INFO   | jvm 1    | 2018/06/07 01:28:17 | 	at java.lang.Class.getDeclaredMethods(Class.java:1975) 
INFO   | jvm 1    | 2018/06/07 01:28:17 | 	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:613) 
INFO   | jvm 1    | 2018/06/07 01:28:17 | 	at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:524) 
INFO   | jvm 1    | 2018/06/07 01:28:17 | 	at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:510) 
INFO   | jvm 1    | 2018/06/07 01:28:17 | 	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.determineCandidateConstructors(AutowiredAnnotationBeanPostProcessor.java:247) 
INFO   | jvm 1    | 2018/06/07 01:28:17 | 	... 42 more 
INFO   | jvm 1    | 2018/06/07 01:28:17 | Caused by: java.lang.ClassNotFoundException: Class 'org.apache.http.HttpRequest' was not found 
INFO   | jvm 1    | 2018/06/07 01:28:17 | 	at jetbrains.buildServer.plugins.classLoaders.TeamCityClassLoader.doLoadClass(TeamCityClassLoader.java:85) 
INFO   | jvm 1    | 2018/06/07 01:28:17 | 	at jetbrains.buildServer.plugins.classLoaders.TeamCityClassLoader.loadClass(TeamCityClassLoader.java:40) 
INFO   | jvm 1    | 2018/06/07 01:28:17 | 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) 
INFO   | jvm 1    | 2018/06/07 01:28:17 | 	... 61 more 
```

**Comment by jakehockey10** [comment]
@andy-culshaw it doesn't look like there is a `lib` folder where you suggest there is.  Can you elaborate on why you think this is the issue and resolution?

**Comment by Zhaph** [comment]
@jakehockey10 That will the line in the logs at the start of the stack trace that states:
> could not find class that it depends on; nested exception is `java.lang.NoClassDefFoundError: org/apache/http/HttpRequest`

I'll give this a go when I'm in the office later. Also ties in with the two or three build failures on the plugin's page which were also unresolved dependencies.

**Comment by andy-culshaw** [comment]
@jakehockey10 I am using a linux build agent. My directory structure looked like this:
/opt/teamcity_build_agent/plugins/teamcity-node-agent-2.0.10
 - lib
    - annotations-13.0.jar
    - gson-2.2.4.jar
    - httpclient-4.2.6.jar
    - kotlin-stdlib-1.2.41.jar
    - teamcity-node-agent-2.0.10.jar
    - teamcity-node-common-2.0.10.jar
 - teamcity-plugin.xml

The stack trace is complaining about org.apache.http.HttpRequest not being found. HTTPClient relies on httpcore (which contains this class) as you can see by the dependencies in the POM - https://search.maven.org/#artifactdetails%7Corg.apache.httpcomponents%7Chttpclient%7C4.2.6%7Cjar. I was initially looking for httpcore-4.2.6.jar, but this version does not exist, so settled for 4.2.5.
When I added the jar and restarted the build agent the dependency was met and it it working as it should

**Comment by Zhaph** [comment]
If you check out the [build errors and fixes here](https://teamcity.jetbrains.com/viewType.html?buildTypeId=bt434&tab=buildTypeHistoryList) that library is required, but is only being included in the tests, not the main plugin, so when the plugin tries to start it can't find it. My java and kotlin is a little non-existent so I'm just guessing...

**Comment by Zhaph** [comment]
I can confirm that the same folder structure exists on a windows build agent with the same 6 dependencies.

`C:\BuildAgent\plugins\teamcity-node-agent-2.0.10\lib`

**Comment by Zhaph** [comment]
As I have a number of build agents, I've taken the following approach for now:

* Download [teamcity-node-2.0.10.zip](https://teamcity.jetbrains.com/repository/download/bt434/1411888:id/teamcity-node-2.0.10.zip)
* Download [HttpCore-4.2.5.jar](http://repo1.maven.org/maven2/org/apache/httpcomponents/httpcore/4.2.5/httpcore-4.2.5.jar)
* Within the plugin zip file, extract the root teamcity-plugin.xml file and update the version number to `2.0.10.1`.
* Within the plugin zip file, open the `teamcity-node-agent-2.0.10.zip` file, and add the `httpcore-4.2.5.jar` folder into the `lib` folder
* Rename the plugin zip file to `teamcity-node-2.0.10.1.zip`
* Upload the updated plugin to TeamCity, which will then roll the updated version of the plugin out to all agents.

**Comment by jonnyzzz** [comment]
Please try 2.0.12

**Comment by Zhaph** [comment]
Hi @jonnyzzz - many thanks for the update, that seems to have worked a treat: new version of the plugin installed and recognised correctly.

**Comment by jonnyzzz** [comment]
I'm sorry it took so long. Thank you for the update!
