### ISSUE TITLE
Failed to start build runner 'jonnyzzz.nvm'

### ISSUE THREAD

**Issue by jfcamach** [jonnyzzz/TeamCity.Node#159]
Hi All

I am getting following error, could someone advise me what could be the root cause?
Node.js version used: 8.12.0

[14:35:01]Step 1/2: Node.js NVM Installer (2m:06s)
[14:35:01][Step 1/2] Download: Fetching NVM (2m:06s)
[14:35:01][Download] Downloading creatonix/nvm...
[14:35:01][Download] from https://github.com/creationix/nvm/archive/v0.7.0.zip
[14:37:07][Step 1/2] Failed to start build runner 'jonnyzzz.nvm'
[14:37:07]
[Step 1/2] org.apache.http.conn.HttpHostConnectException: Connection to https://github.com refused
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:190)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:294)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:643)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:479)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:906)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:805)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:784)
	at com.jonnyzzz.teamcity.plugins.node.agent.nvm.HttpClientWrapperImpl.execute(HttpClient.kt:149)
	at com.jonnyzzz.teamcity.plugins.node.agent.nvm.NVMDownloader.downloadNVM(NVM.kt:56)
	at com.jonnyzzz.teamcity.plugins.node.agent.nvm.NVMRunner$createBuildProcess$$inlined$logging$lambda$lambda$1.invoke(NVM.kt:105)
	at com.jonnyzzz.teamcity.plugins.node.agent.nvm.NVMRunner$createBuildProcess$$inlined$logging$lambda$lambda$1.invoke(NVM.kt:90)
	at com.jonnyzzz.teamcity.plugins.node.agent.processes.CompositeProcessBuilderImpl$process$1.waitForImpl(BuildProcessBuilder.kt:91)
	at com.jonnyzzz.teamcity.plugins.node.agent.processes.BuildProcessBase.waitFor(BuildProcess.kt:47)
	at com.jonnyzzz.teamcity.plugins.node.agent.processes.DelegatingBuildProcess.waitForImpl(BuildProcess.kt:80)
	at com.jonnyzzz.teamcity.plugins.node.agent.processes.BuildProcessBase.waitFor(BuildProcess.kt:47)
	at com.jonnyzzz.teamcity.plugins.node.agent.processes.CompositeBuildProcessImpl.waitForImpl(CompositeBuildProcess.kt:58)
	at com.jonnyzzz.teamcity.plugins.node.agent.processes.BuildProcessBase.waitFor(BuildProcess.kt:47)
	at jetbrains.buildServer.agent.impl.buildStages.runnerStages.start.CallRunnerStage.doBuildStage(CallRunnerStage.java:75)
	at jetbrains.buildServer.agent.impl.buildStages.RunnerStagesExecutor$1.callStage(RunnerStagesExecutor.java:25)
	at jetbrains.buildServer.agent.impl.buildStages.RunnerStagesExecutor$1.callStage(RunnerStagesExecutor.java:18)
	at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.callRunStage(StagesExecutor.java:78)
	at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.doStages(StagesExecutor.java:37)
	at jetbrains.buildServer.agent.impl.buildStages.RunnerStagesExecutor.doStages(RunnerStagesExecutor.java:18)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.RunnerContextExecutor.callRunnerStages(RunnerContextExecutor.java:43)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.StepExecutor.processNextStep(StepExecutor.java:25)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.executeRunnerStep(ForEachBuildRunnerStage.java:138)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.runStep(ForEachBuildRunnerStage.java:123)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.executeBuildRunners(ForEachBuildRunnerStage.java:83)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.doBuildStage(ForEachBuildRunnerStage.java:44)
	at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor$1.callStage(BuildStagesExecutor.java:31)
	at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor$1.callStage(BuildStagesExecutor.java:24)
	at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.callRunStage(StagesExecutor.java:78)
	at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.doStages(StagesExecutor.java:37)
	at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor.doStages(BuildStagesExecutor.java:24)
	at jetbrains.buildServer.agent.impl.BuildRunActionImpl.doStages(BuildRunActionImpl.java:75)
	at jetbrains.buildServer.agent.impl.BuildRunActionImpl.runBuild(BuildRunActionImpl.java:55)
	at jetbrains.buildServer.agent.impl.BuildAgentImpl.doActualBuild(BuildAgentImpl.java:295)
	at jetbrains.buildServer.agent.impl.BuildAgentImpl.access$100(BuildAgentImpl.java:53)
	at jetbrains.buildServer.agent.impl.BuildAgentImpl$1.run(BuildAgentImpl.java:259)
	at java.lang.Thread.run(Thread.java:662)
Caused by: java.net.ConnectException: Connection timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:351)
	at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:213)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:200)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:366)
	at java.net.Socket.connect(Socket.java:529)
	at com.sun.net.ssl.internal.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:570)
	at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:414)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:180)
	... 39 more
[14:37:07][Step 1/2] Step Node.js NVM Installer failed with unexpected error
[14:37:07]Step 2/2: integration tests (Node.js NPM)
[14:37:07][Step 2/2] Build step integration tests (Node.js NPM) is skipped because the previous step has failed

**Comment by jonnyzzz** [comment]
It attempts to download the NVM from the internet. Please check you have
the connection. There is the parameter in the NVM build feature to supply
an alternative URL, which can be in your local network

**Comment by jfcamach** [comment]
Hello.

Thanks for your response.
Is there any documentation about this feature? I mean how to configure
alternative features, how it works, etc

Thanks
