### ISSUE TITLE
Upgrade to TeamCity 2024.12 (build 174331) breaks plugin

### ISSUE THREAD

**Issue by rsgAsif** [jonnyzzz/TeamCity.Node#194]
Hi, I have just upgraded TeamCity to the newest version and this has broken your plugin version 2.0.27. I am running both the TeamCtiy Server and agent on a single Windows Server 2022 machine

Below is the output, Please advise

Step 5/9: Install Node (Node.js NVM Installer)
16:59:59   Download: Fetching NVM
16:59:59     Downloading nvm-sh/nvm...
16:59:59     from https://github.com/nvm-sh/nvm/archive/v0.39.2.zip
16:59:59     NVM downloaded into D:\TeamCity\buildAgent\system\jonnyzzz.nvm
16:59:59   Install: Installing Node.js v22.5.1
16:59:59   java.lang.IllegalStateException: Failed to find build runner settings with id custom_3
    at org.jetbrains.teamcity.docker.BuildRunnerSettingsFinderKt.findRunnerSettings(BuildRunnerSettingsFinder.kt:14)
    at org.jetbrains.teamcity.docker.DockerWrapperSettings$Factory.from(DockerWrapperSettings.kt:68)
    at org.jetbrains.teamcity.docker.wrapper.DockerCommandLineWrapper.process(DockerCommandLineWrapper.kt:52)
    at jetbrains.buildServer.agent.runner2.GenericCommandLineBuildProcess.customize(GenericCommandLineBuildProcess.java:158)
    at jetbrains.buildServer.agent.runner2.GenericCommandLineBuildProcess.executeProcess(GenericCommandLineBuildProcess.java:81)
    at jetbrains.buildServer.agent.runner2.GenericCommandLineBuildProcess.waitFor(GenericCommandLineBuildProcess.java:293)
    at com.jonnyzzz.teamcity.plugins.node.agent.processes.DelegatingBuildProcess.waitForImpl(BuildProcess.kt:80)
    at com.jonnyzzz.teamcity.plugins.node.agent.processes.BuildProcessBase.waitFor(BuildProcess.kt:47)
    at com.jonnyzzz.teamcity.plugins.node.agent.processes.CompositeBuildProcessImpl.waitForImpl(CompositeBuildProcess.kt:58)
    at com.jonnyzzz.teamcity.plugins.node.agent.processes.CompositeBuildProcessImpl.waitForImpl(CompositeBuildProcess.kt:68)
    at com.jonnyzzz.teamcity.plugins.node.agent.processes.BuildProcessBase.waitFor(BuildProcess.kt:47)
    at jetbrains.buildServer.agent.impl.buildStages.runnerStages.start.CallRunnerStage.doBuildStage(CallRunnerStage.java:61)
    at jetbrains.buildServer.agent.impl.buildStages.RunnerStagesExecutor$1.callStage(RunnerStagesExecutor.java:27)
    at jetbrains.buildServer.agent.impl.buildStages.RunnerStagesExecutor$1.callStage(RunnerStagesExecutor.java:18)
    at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.callRunStage(StagesExecutor.java:76)
    at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.doStages(StagesExecutor.java:35)
    at jetbrains.buildServer.agent.impl.buildStages.RunnerStagesExecutor.doStages(RunnerStagesExecutor.java:18)
    at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.RunnerContextExecutor.executeBuildStepStages(RunnerContextExecutor.java:45)
    at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.RunAllBuildStepsStage.runBuildStep(RunAllBuildStepsStage.java:195)
    at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.RunAllBuildStepsStage.runStep(RunAllBuildStepsStage.java:181)
    at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.RunAllBuildStepsStage.executeBuildRunners(RunAllBuildStepsStage.java:131)
    at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.RunAllBuildStepsStage.doBuildStage(RunAllBuildStepsStage.java:58)
    at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor$1.callStage(BuildStagesExecutor.java:33)
    at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor$1.callStage(BuildStagesExecutor.java:24)
    at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.callRunStage(StagesExecutor.java:76)
    at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.doStages(StagesExecutor.java:35)
    at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor.doStages(BuildStagesExecutor.java:24)
    at jetbrains.buildServer.agent.impl.BuildRunActionImpl.doStages(BuildRunActionImpl.java:97)
    at jetbrains.buildServer.agent.AgentOperationModeEx.executeRunnerStages(AgentOperationModeEx.java:47)
    at jetbrains.buildServer.agent.impl.BuildRunActionImpl.runBuild(BuildRunActionImpl.java:68)
    at jetbrains.buildServer.agent.impl.BuildAgentImpl.doActualBuild(BuildAgentImpl.java:350)
    at jetbrains.buildServer.agent.impl.BuildAgentImpl.access$100(BuildAgentImpl.java:62)
    at jetbrains.buildServer.agent.impl.BuildAgentImpl$1.run(BuildAgentImpl.java:299)
    at java.base/java.lang.Thread.run(Thread.java:833)
16:59:59   Failed to start build runner 'jonnyzzz.nvm'
16:59:59   Step Install Node (Node.js NVM Installer) failed with unexpected error

**Comment by ChrisMorisette** [comment]
Also facing this same issue after upgrading.

**Comment by code-affinity** [comment]
After upgrading TeamCity to 2024.12, we are also having the same problem ("Failed to find build runner settings with id custom_(whatever)" with all of our builds that use jonnyzzz.nvm or jonnyzzz.npm.  We are running plugin version 2.0.27.

**Comment by DieDrachenfaenger** [comment]
Same problem here.

**Comment by nirkoren** [comment]
Same here

**Comment by rsgAsif** [comment]
FYI as a temp workaround i have disabled the build step and added a new one, which is a Simple command execution, where i simply added the following to the Custom Script text area

nvm install 22.5.1
nvm use 22.5.1

If the plugin isnt fixed i will probably conitnue to use this, but repace the hard coded version numbers with a TC variable

**Comment by pavel-krizskii** [comment]
Hi, sorry for the inconvenience!

We will look at the issue and will come up with the fix soon. You can track the progress here: https://youtrack.jetbrains.com/issue/TW-91309 

As a temporary workaround, could you please follow these steps:
1. Go to `Admin` -> `Projects` -> `<Root Project>` -> `Parameters` -> `Add new parameter`
2. Specify `teamcity.internal.docker.containerReuse.buildStepGroup.enabled` as Name and `false` as Value

The try to run the build again. Please let me know if the workaround works for you

**Comment by code-affinity** [comment]
The workaround worked for us.  Thank you for your prompt support.

**Comment by suhrab** [comment]
@pavel-krizskii Workaround worked. Thank you

I do update my company Teamcity server regularly
This plugin stopped working few times this year after Teamcity Server upgrade
Sharing another workaround that does not use this plugin NVM feature:

1. Install nvm for linux for user that runs Teamcity agent
2. Add new build step. Type - Command line
3. Enter build script content:

> . ~/.nvm/nvm.sh
nvm use 16
eval ${TEAMCITY_CAPTURE_ENV}

where 16 is the node version

**Comment by rsgAsif** [comment]
Hi i can confirm that the workaround has worked for me, apologies for the delayed confirmation.

**Comment by VitaliAndrushkevich** [comment]
> Hi, sorry for the inconvenience!
> 
> We will look at the issue and will come up with the fix soon. You can track the progress here: https://youtrack.jetbrains.com/issue/TW-91309
> 
> As a temporary workaround, could you please follow these steps:
> 
> 1. Go to `Admin` -> `Projects` -> `<Root Project>` -> `Parameters` -> `Add new parameter`
> 2. Specify `teamcity.internal.docker.containerReuse.buildStepGroup.enabled` as Name and `false` as Value
> 
> The try to run the build again. Please let me know if the workaround works for you

This helped, thank you!

**Comment by dploeger** [comment]
Hey, the youtrack issue https://youtrack.jetbrains.com/issue/TW-91309 isn't visible to the public I think. So we can't really follow the progress there. :)

<img width="203" alt="grafik" src="https://github.com/user-attachments/assets/ffeb3468-3686-4868-9874-788aee9b57a1" />

Maybe this could be changed.

**Comment by dploeger** [comment]
Sorry, I seem to have mistinterpreted the Youtrack status. Apparently everybody CAN check the issue but it isn't filled anyhow. No comments etc. Is that expected, @pavel-krizskii ?

**Comment by pavel-krizskii** [comment]
@dploeger Hi, I've added a comment in the task: https://youtrack.jetbrains.com/issue/TW-91309/TeamCity.Node-plugin-fails-with-Failed-to-find-build-runner-settings-error#focus=Comments-27-11387877.0-0 

The issues is fixed starting from `TeamCity 2024.12.1` (which will be released soon)
