### ISSUE TITLE
require() not working with Source Code execution

### ISSUE THREAD

**Issue by tcrosen** [jonnyzzz/TeamCity.Node#66]
It doesn't seem `require()` works when using the Node.js runner with Script set to Source Code.
I can install local modules or global modules but require will not find them.  Instead I always get this error:

```
[18:47:45][Step 4/5] 
[18:47:45][Step 4/5] module.js:340
[18:47:45][Step 4/5]     throw err;
[18:47:45][Step 4/5]           ^
[18:47:45][Step 4/5] Error: Cannot find module '<module name>'
[18:47:45][Step 4/5]     at Function.Module._resolveFilename (module.js:338:15)
[18:47:45][Step 4/5]     at Function.Module._load (module.js:280:25)
[18:47:45][Step 4/5]     at Module.require (module.js:364:17)
[18:47:45][Step 4/5]     at require (module.js:380:17)
[18:47:45][Step 4/5]     at Object.<anonymous> (D:\TeamCity\Agent\buildAgent4\temp\agentTmp\node3473540003029466460.js:1:75)
[18:47:45][Step 4/5]     at Module._compile (module.js:456:26)
[18:47:45][Step 4/5]     at Object.Module._extensions..js (module.js:474:10)
[18:47:45][Step 4/5]     at Module.load (module.js:356:32)
[18:47:45][Step 4/5]     at Function.Module._load (module.js:312:12)
[18:47:45][Step 4/5]     at Function.Module.runMain (module.js:497:10)
[18:47:45][Step 4/5] Process exited with code 8
```

is this expected behaviour or am I doing something wrong?

**Comment by tcrosen** [comment]
I should add that I'm executing the script from the same directory as `node_modules` are installed, though it shouldn't matter since `require()` looks for `node_modules` locally then cascades up the directory tree.

**Comment by jonnyzzz** [comment]
The bug here is that Node.js runner uses build agent temp directory to
create the file, not the working directory. Do you know if this could be
fixed by settings some commandline arguments/environment variables?

Best regards,
Eugene Petrenko

**Comment by tcrosen** [comment]
Do you mean Node command line args/env variables?  I'm not sure.  I'm surprised global packages don't work though, since my understanding is that's the fallback when `require` can't find local files.  Maybe using an artifact dependency will work, I'll see what I can figure out and update here if I solve the problem.

**Comment by jonnyzzz** [comment]
I changed the code to use working directory to generate .js file in. This should fix your case. 
The change affects both node.js and Phantom.js build runners
